### ISSUE TITLE
Events management integration

### ISSUE THREAD

**Issue by murwaneisa** [murwaneisa/HKIF-APP#78]
Dependent Branch(es)
feature/events-integration

Functionality
integrate the events management with the server

Additional Notes

**Comment by zzfz1** [comment]
Formik

**Comment by zzfz1** [comment]
@murwaneisa 

There's no address filed in the event model currently.

![Image](https://github.com/murwaneisa/HKIF-APP/assets/86393880/93957e95-51ca-4dde-bfd0-87bed8c20903)

**Comment by murwaneisa** [comment]
The event must  have an address, can you fix it ,or should I make it as a task

**Comment by zzfz1** [comment]
I'll fix it, no worries.

**Comment by zzfz1** [comment]
@murwaneisa 

Is the admin allowed to join an event?

Now in the event details it shows the button even if with an admin account.

![Image](https://github.com/murwaneisa/HKIF-APP/assets/86393880/b3e41bb2-e882-4edd-ba83-0e0f64114f93)

I'll **leave it** for now since it doesn't seem to be a part of the **event management**.

**Comment by murwaneisa** [comment]
Yeah! Just leave it, there is a bug error we need to fix for the naviagtion between the admin event and user event

**Comment by zzfz1** [comment]
@murwaneisa @ahmedmohd957 

Do we really need the date to be in this format?

![Image](https://github.com/murwaneisa/HKIF-APP/assets/86393880/d234a057-356e-4334-a97d-006825fb08d8)

It's much easier to validate and process to a timestamp if we use 'YYYY-MM-DD' format.

**Comment by ahmedmohd957** [comment]
@zzfz1 No, you can change it.
